version: '3'

services:
  nginx:
    image: yosmy/nginx
    container_name: mundorecarga_api_nginx
    working_dir: /var/www
  php:
    image: yosmy/php
    container_name: mundorecarga_api_php
    working_dir: /var/www
    user: "$UID:$GID"
  mongo:
    image: yosmy/mongo
    container_name: mundorecarga_api_mongo
    volumes:
      - ../var/db:/data/db
  imaginary:
    image: h2non/imaginary:1
    container_name: mundorecarga_api_imaginary
    user: "$UID:$GID"

