version: '3'

services:
  nginx:
    volumes:
      - ./nginx/default_prod.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=api.mundorecarga.com
      - LETSENCRYPT_HOST=api.mundorecarga.com
      - LETSENCRYPT_EMAIL=contact@mundorecarga.com
    restart: always
  php:
    volumes:
      - ./php/php_prod.ini:/usr/local/etc/php/php.ini
      - ../:/var/www/
    restart: always
  mongo:
    restart: always
  cron:
    image: yosmy/php
    container_name: mundorecarga_api_cron
    volumes:
      - ../:/var/www
      - ./php/php_prod.ini:/usr/local/etc/php/php.ini
      - ./cron:/root/cron
    networks:
      - backend
    working_dir: /var/www
    entrypoint: /root/cron/entrypoint.sh
    restart: always
  imaginary:
    restart: always
#  mongo-express:
#    image: mongo-express
#    container_name: mundorecarga_api_mongo_express
#    depends_on:
#      - mongo
#    networks:
#      - frontend
#      - backend
#    environment:
#      - ME_CONFIG_OPTIONS_READONLY=true
#      - ME_CONFIG_SITE_BASEURL=/db/
#    expose:
#      - 8081